# Inserts a blank line between shell prompts
add_newline = true

format = """$username$directory$fill $git_status$git_branch$python$nodejs$cmd_duration$time$jobs
$status$character"""

[fill]
symbol = "─"
style = "dimmed white"

[cmd_duration]
min_time = 1_000
style = "yellow"

[time]
disabled = false
style = "blue"

[status]
disabled = false
