# Helpers
# Checks if a name is a command, function, or alias.
function is-callable {
  (( $+commands[$1] || $+functions[$1] || $+aliases[$1] || $+builtins[$1] ))
}

# Python
is-callable "pyenv" && eval "$(pyenv init --path)"
